# Generated by Django 3.1.7 on 2021-03-23 18:54

import custom_login.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_login', '0004_myuser_profile_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='is_block',
            field=models.BooleanField(default=False, verbose_name='بلاک بودن'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='profile_pic',
            field=models.ImageField(blank=True, default='site/unnamed.png', null=True, upload_to=custom_login.models.upload_image_path, verbose_name='تصویر پروفایل'),
        ),
    ]
