# Generated by Django 3.1.7 on 2021-03-12 09:59

from django.db import migrations, models
import yad.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Yad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='مرحوم', max_length=150, verbose_name='پیشوند')),
                ('name', models.CharField(max_length=150, verbose_name='نام')),
                ('family', models.CharField(max_length=150, verbose_name='نام خانوادگی')),
                ('local', models.CharField(blank=True, max_length=150, null=True, verbose_name='محل دفن')),
                ('death_time', models.DateTimeField(auto_now=True, null=True, verbose_name='تاریخ فوت')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('master_image', models.ImageField(blank=True, null=True, upload_to=yad.models.upload_image_path, verbose_name='تصویر اصلی')),
                ('favio_image', models.ImageField(blank=True, null=True, upload_to=yad.models.upload_image_path, verbose_name='تصویر اشتراک گذاری')),
                ('active', models.BooleanField(default=False, verbose_name='فعال / غیرفعال')),
                ('visit_count', models.IntegerField(default=0, verbose_name='تعداد بازدید')),
                ('salavat_count', models.IntegerField(default=0, verbose_name='تعداد صلوات')),
                ('fatehe_count', models.IntegerField(default=0, verbose_name='تعداد فاتحه')),
                ('quran_count', models.IntegerField(default=0, verbose_name='تعداد صفحات قرآن')),
            ],
            options={
                'verbose_name': 'یادبود',
                'verbose_name_plural': 'یادبودها',
            },
        ),
    ]
