# Generated by Django 3.1.7 on 2021-03-20 08:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('yad', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='yad',
            name='quran_count',
        ),
        migrations.AddField(
            model_name='yad',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
    ]
