# Generated by Django 3.1.7 on 2021-03-20 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yad', '0002_auto_20210320_0840'),
    ]

    operations = [
        migrations.AddField(
            model_name='yad',
            name='quran_count',
            field=models.IntegerField(default=0, verbose_name='تعداد صفحات قرآن'),
        ),
    ]
