# Generated by Django 3.1.7 on 2021-03-21 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yad', '0005_auto_20210321_0620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yad',
            name='death_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاریخ فوت'),
        ),
    ]
