# Generated by Django 3.1.7 on 2021-03-29 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yad', '0006_auto_20210321_0621'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='yad',
            name='death_time',
        ),
        migrations.RemoveField(
            model_name='yad',
            name='favio_image',
        ),
        migrations.RemoveField(
            model_name='yad',
            name='local',
        ),
    ]
