# Generated by Django 3.1.7 on 2021-03-29 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yad', '0007_auto_20210329_1031'),
    ]

    operations = [
        migrations.AddField(
            model_name='yad',
            name='death_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ فوت / شهادت'),
        ),
    ]
