# Generated by Django 3.1.7 on 2021-03-29 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mycity', '0002_auto_20210329_1031'),
        ('yad', '0008_yad_death_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='yad',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shahr', to='mycity.city', verbose_name='شهر'),
        ),
        migrations.AddField(
            model_name='yad',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ostan', to='mycity.state', verbose_name='استان'),
        ),
    ]
