# Generated by Django 3.1.7 on 2021-04-02 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yad', '0009_auto_20210329_1036'),
    ]

    operations = [
        migrations.AddField(
            model_name='yad',
            name='is_featured',
            field=models.BooleanField(default=False, verbose_name='ویژه'),
        ),
    ]
