# Generated by Django 3.1.7 on 2024-09-12 17:53

import article.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_auto_20240912_1735'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='article_imge',
            field=models.ImageField(blank=True, null=True, upload_to=article.models.upload_article_image_path, verbose_name='تصویر مقاله'),
        ),
        migrations.AddField(
            model_name='article',
            name='article_kinde',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='نوع'),
        ),
        migrations.AddField(
            model_name='article',
            name='article_text',
            field=models.TextField(blank=True, null=True, verbose_name='متن مقاله'),
        ),
    ]
