# Generated by Django 3.1.7 on 2021-03-19 08:13

from django.db import migrations, models
import quran.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quran',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.IntegerField(default=1, verbose_name='صفحه')),
                ('joz', models.IntegerField(default=1, verbose_name='جز')),
                ('image', models.ImageField(blank=True, null=True, upload_to=quran.models.upload_image_path, verbose_name='تصویر ')),
                ('is_read', models.BooleanField(default=False, verbose_name='خوانده شده/خوانده نشده')),
                ('read_count', models.IntegerField(default=0, verbose_name='دفعات خوانده شده')),
            ],
            options={
                'verbose_name': 'صفحه قرآن',
                'verbose_name_plural': 'صفححات قرآن',
            },
        ),
    ]
