# Generated by Django 3.1.7 on 2021-03-19 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quran', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quran_set',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_count', models.IntegerField(default=0, verbose_name='دفعات ختم کل')),
            ],
            options={
                'verbose_name': 'ختم کل',
                'verbose_name_plural': 'ختم های کل',
            },
        ),
        migrations.AlterModelOptions(
            name='quran',
            options={'verbose_name': 'صفحه قرآن', 'verbose_name_plural': 'صفحات قرآن'},
        ),
    ]
