# Generated by Django 3.1.7 on 2021-03-21 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quran', '0002_auto_20210319_0819'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quran_set',
            options={'verbose_name': 'تنظیم ذکر', 'verbose_name_plural': 'تنظیمات ذکر و قرآن'},
        ),
        migrations.AddField(
            model_name='quran_set',
            name='total_salavat',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='quran_set',
            name='total_count',
            field=models.IntegerField(verbose_name='دفعات ختم کل'),
        ),
    ]
