# Generated by Django 3.1.7 on 2021-03-21 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quran', '0003_auto_20210321_1301'),
    ]

    operations = [
        migrations.AddField(
            model_name='quran_set',
            name='total_fatehe',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
