# Generated by Django 3.1.7 on 2021-03-21 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quran', '0004_quran_set_total_fatehe'),
    ]

    operations = [
        migrations.AddField(
            model_name='quran_set',
            name='total_yadbood',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
