# Generated by Django 3.1.7 on 2021-03-21 13:16

from django.db import migrations, models
import quran.models


class Migration(migrations.Migration):

    dependencies = [
        ('quran', '0005_quran_set_total_yadbood'),
    ]

    operations = [
        migrations.CreateModel(
            name='Site_detting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, null=True, upload_to=quran.models.upload_set_image_path, verbose_name='لوگو')),
            ],
        ),
    ]
