# Generated by Django 3.1.7 on 2021-03-21 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quran', '0006_site_detting'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Site_detting',
            new_name='Site_setting',
        ),
    ]
