# Generated by Django 3.1.7 on 2021-03-21 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quran', '0007_auto_20210321_1320'),
    ]

    operations = [
        migrations.AddField(
            model_name='site_setting',
            name='about',
            field=models.TextField(blank=True, null=True, verbose_name='درباره ما'),
        ),
    ]
