# Generated by Django 3.1.7 on 2021-03-29 12:35

from django.db import migrations, models
import quran.models


class Migration(migrations.Migration):

    dependencies = [
        ('quran', '0009_site_setting_site_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='site_setting',
            name='yad_image_default',
            field=models.ImageField(blank=True, null=True, upload_to=quran.models.upload_set_image_path, verbose_name='تصویر '),
        ),
    ]
