# Generated by Django 3.1.7 on 2021-04-02 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quran', '0010_site_setting_yad_image_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='quran',
            name='is_joz_readable',
            field=models.BooleanField(default=True, verbose_name='جزء قابل خواندن است'),
        ),
    ]
