# Generated by Django 3.1.7 on 2021-04-09 18:21

from django.db import migrations, models
import quran.models


class Migration(migrations.Migration):

    dependencies = [
        ('quran', '0011_quran_is_joz_readable'),
    ]

    operations = [
        migrations.AddField(
            model_name='quran',
            name='sound',
            field=models.FileField(blank=True, null=True, upload_to=quran.models.upload_sound_path, verbose_name='صوت قرآن'),
        ),
    ]
