# Generated by Django 3.1.7 on 2021-04-15 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quran', '0012_quran_sound'),
    ]

    operations = [
        migrations.AddField(
            model_name='site_setting',
            name='conditions',
            field=models.TextField(blank=True, null=True, verbose_name='قوانین ومقررات'),
        ),
    ]
