# Generated by Django 3.1.7 on 2021-03-26 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('yad', '0006_auto_20210321_0621'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marasem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='عنوان مراسم')),
                ('address', models.TextField(blank=True, null=True, verbose_name='آدرس')),
                ('event_date', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ مراسم')),
                ('starttime', models.TimeField(blank=True, null=True, verbose_name='ساعت شروع مراسم')),
                ('finishtime', models.TimeField(blank=True, null=True, verbose_name='ساعت پایان مراسم')),
                ('active', models.BooleanField(default=True, verbose_name='فعال / غیرفعال')),
                ('yad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='yad.yad', verbose_name='یادبود')),
            ],
        ),
    ]
