# Generated by Django 3.1.7 on 2021-03-28 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mycity', '0001_initial'),
        ('marasem', '0002_auto_20210327_1807'),
    ]

    operations = [
        migrations.AddField(
            model_name='marasem',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='city', to='mycity.city', verbose_name='شهر'),
        ),
        migrations.AddField(
            model_name='marasem',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='state', to='mycity.state', verbose_name='استان'),
        ),
    ]
