# Generated by Django 3.1.7 on 2021-03-29 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycity', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(max_length=40, verbose_name='نام شهر'),
        ),
    ]
