"""
Django settings for yadeo project.

Generated by 'django-admin startproject' using Django 3.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""

from pathlib import Path

#-----------------------------------------------------
import os
from django.contrib.messages import constants as messages

MESSAGE_TAGS = {
    messages.ERROR : 'danger',
    messages.INFO : 'success'
}




#-----------------------------------------------------








# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'n+r60@)s2rr00d3$wd*ky2&xzn2ygqy!22_r+0nr(%=w@w#g+='

# SECURITY WARNING: don't run with debug turned on in production!
# DEBUG = True
DEBUG = False

ALLOWED_HOSTS = ['www.yadeo.ir','yadeo.ir']
#---------------------------------------------------
AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'custom_login.mybackend.ModelBackend',
]
#-----------------------------------------

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'jalali_date',
    'django.contrib.sitemaps',
    'django.contrib.humanize',

    
    # 'bootstrap_datepicker_plus'
    #my app
    'custom_login.apps.CustomLoginConfig',
    'background_task',
    'django_render_partial',
    'yad',
    'quran',
    'mycity',
    'profile_page',
    'marasem',
    'contact'


]
#
# BOOTSTRAP4 = {
#     'include_jquery': True,
# }






MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'yadeo.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
    # ----------------------------------------------------

        'DIRS': [os.path.join(BASE_DIR, 'templates')],
# ----------------------------------------------------
#         'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.request',
            ],
        },
    },
]

WSGI_APPLICATION = 'yadeo.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'yadeoir_yadeo',
        'USER' : 'yadeoir_yadeo_user8',
        'PASSWORD': ')a7=.Tf{{![W',
        'HOST' : 'localhost',
        'PORT': '3306',
        'OPTIONS':{
            'sql_mode':'STRICT_ALL_TABLES'}
        
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

# LANGUAGE_CODE = 'en-us'
LANGUAGE_CODE = 'fa-ir'

# TIME_ZONE = 'UTC'
TIME_ZONE = 'Asia/Tehran'

USE_I18N = True

# USE_L10N = True
USE_L10N = False

# USE_TZ = True
USE_TZ = False




# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/


#STATIC_URL = '/site_statics/'
STATIC_URL = '/static/'


STATICFILES_DIRS = [
    os.path.join(BASE_DIR,"assets")
]
#STATIC_ROOT= os.path.join(BASE_DIR,"static_cdn" , "static_root")


STATIC_ROOT= '/home/yadeoir/public_html/static/'



MEDIA_URL = '/media/'

#MEDIA_ROOT = os.path.join(BASE_DIR, "static_cdn", "media_root")

MEDIA_ROOT ='/home/yadeoir/public_html/media'







AUTH_USER_MODEL = 'custom_login.MyUser'

Kavenegar_API = '50795A38675936485546436B3652784C57396953516F616D544C4B4F35654E35712F2B3379646B4A4E474D3D'
# Kavenegar_API = '**********************************************************'




# defaults
JALALI_DATE_DEFAULTS = {
   'Strftime': {
        'date': '%y/%m/%d',
        'datetime': '%H:%M:%S _ %y/%m/%d',
    },
    'Static': {
        'js': [
            # loading datepicker
            'admin/js/django_jalali.min.js',
            # OR
            # 'admin/jquery.ui.datepicker.jalali/scripts/jquery.ui.core.js',
            # 'admin/jquery.ui.datepicker.jalali/scripts/calendar.js',
            # 'admin/jquery.ui.datepicker.jalali/scripts/jquery.ui.datepicker-cc.js',
            # 'admin/jquery.ui.datepicker.jalali/scripts/jquery.ui.datepicker-cc-fa.js',
            # 'admin/js/main.js',
        ],
        'css': {
            'all': [
                'admin/jquery.ui.datepicker.jalali/themes/base/jquery-ui.min.css',
            ]
        }
    },
}





USE_THOUSAND_SEPARATOR = True
